version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "80:5000"

  db:
    image: mysql:8
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
# volume allows to store the saved data after the containers have been stopped.
# The DB will not be cleaned until we explicitly tell to docker compose to drop the container's volumes.
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro